Use [IDPCCS]
Go

ALTER TABLE CCS_CONFIGCODELIST ADD CONSTRAINT PK_CCS_CONFIGCODELIST PRIMARY KEY (Id)
ALTER TABLE CCS_Transaction ADD CONSTRAINT PK_CCS_Transaction PRIMARY KEY (Id)
ALTER TABLE CCS_Calendar ADD CONSTRAINT PK_CCS_Calendar PRIMARY KEY (Id)
ALTER TABLE CCS_Config ADD CONSTRAINT PK_CCS_Config PRIMARY KEY (Id)
ALTER TABLE CCS_Parameter ADD CONSTRAINT PK_CCS_Parameter PRIMARY KEY (Id)
ALTER TABLE CCS_CARDTYPE ADD CONSTRAINT PK_CCS_CARDTYPE PRIMARY KEY (Id)
ALTER TABLE CCS_CARDLEVEL ADD CONSTRAINT PK_CCS_CARDLEVEL PRIMARY KEY (Id)
ALTER TABLE CCS_CARDCONFIG ADD CONSTRAINT PK_CCS_CARDCONFIG PRIMARY KEY (Id)
ALTER TABLE CCS_CARDLIMIT ADD CONSTRAINT PK_CCS_CARDLIMIT PRIMARY KEY (Id)
ALTER TABLE CCS_TRANSACTIONLIMIT ADD CONSTRAINT PK_CCS_TRANSACTIONLIMIT PRIMARY KEY (Id)
ALTER TABLE RTE_CITY ADD CONSTRAINT PK_RTE_CITY PRIMARY KEY (Id)
ALTER TABLE RTE_ROUTE ADD CONSTRAINT PK_RTE_ROUTE PRIMARY KEY (Id)
ALTER TABLE SYS_SERVICETYPE ADD CONSTRAINT PK_SYS_SERVICETYPE PRIMARY KEY (Id)
ALTER TABLE SYS_VENDORMACHINE ADD CONSTRAINT PK_SYS_VENDORMACHINE PRIMARY KEY (Id)
ALTER TABLE PMT_CONFIG ADD CONSTRAINT PK_PMT_CONFIG PRIMARY KEY (Id)
ALTER TABLE CCS_CARDUSER ADD CONSTRAINT PK_CCS_CARDUSER PRIMARY KEY (Id)